#!/bin/bash

command -v mvn >/dev/null 2>&1 || { echo >&2 "Maven is required for setup. Aborting."; exit 1; }

mvn clean install

mkdir trainer/
mkdir cli/
cp tak-ai/target/tak-ai*.jar trainer/
cp tak-cli/target/tak-cli*.jar cli/
