#!/bin/bash

command -v mvn >/dev/null 2>&1 || { echo >&2 "Maven is required for setup. Aborting."; exit 1; }

mvn clean install

mkdir -p trainer/
mkdir -p cli/
mkdir -p server/
cp tak-ai/target/tak-ai*.jar trainer/
cp tak-cli/target/tak-cli*.jar cli/
cp tak-server/target/tak-server*.jar server/
