#!/bin/bash

command -v mvn >/dev/null 2>&1 || { echo >&2 "Maven is required for setup. Aborting."; exit 1; }

cd tak-engine
mvn clean install
cd ../tak-ai
mvn clean install
cd ../tak-cli
mvn clean install
